In [1]:
import numpy as np

## 2.1 NumPy数组对象

In [2]:
a = np.arange(5)

In [3]:
# 获取数据类型
a.dtype

dtype('int64')

In [4]:
# 获取数据维度
a.shape

(5,)

## 2.2 动手实践: 创建多维数组

In [5]:
# 创建2*2的多维数组
m = np.array([np.arange(2), np.arange(2)])

In [6]:
m

array([[0, 1],
       [0, 1]])

In [7]:
m.shape

(2, 2)

In [8]:
# 创建3*3的多维数组
n = np.array([np.arange(3), np.arange(3), np.arange(3)])

In [9]:
n

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [10]:
n.shape

(3, 3)

### 2.2.1 选取数组元素

In [11]:
a = np.array([[1,2],[3,4]])

In [12]:
a

array([[1, 2],
       [3, 4]])

In [13]:
a[0,0]

1

In [14]:
a[0,1]

2

In [15]:
a[1,0]

3

In [16]:
a[1,1]

4

### 2.2.2 NumPy数据类型

In [17]:
np.float64(42)

42.0

In [18]:
np.int8(42.0)

42

In [19]:
np.bool(42)

True

In [20]:
np.bool(0)

False

In [21]:
np.bool(42.0)

True

In [22]:
np.float(True)

1.0

In [23]:
np.float(False)

0.0

In [24]:
np.arange(8, dtype=np.uint32)

array([0, 1, 2, 3, 4, 5, 6, 7], dtype=uint32)

### 2.2.3 数据类型对象

In [25]:
# 使用dtype类的itemsize属性给出单个元素在内存中占用的字节数
b = np.array([[1,2,3], [3,4,5], [5,6,7]], dtype=np.uint64)
b.dtype.itemsize

8

### 2.2.4 字符编码

In [26]:
# 创建了一个单精度浮点数数组
np.arange(9, dtype = 'f')

array([0., 1., 2., 3., 4., 5., 6., 7., 8.], dtype=float32)

In [27]:
# 创建一个复数数组
np.arange(5, dtype = 'D')

array([0.+0.j, 1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

### 2.2.5 自定义数据类型